name: Maven Package

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 24 & configure Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          server-id: github              # must match distributionManagement/repository/id in pom.xml
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GH_TOKEN }}
          # (optional) settings-path: ${{ github.workspace }} 

      - name: Build & Deploy
        run: mvn clean deploy
